module.exports = {
  PROJECTS_RECEIVED: "PROJECTS_RECEIVED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_DESTROYED: "PROJECT_DESTROYED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJ_ERROR: "PROJ_ERROR"
};
